# Site settings
title: Tute Costa
tagline: De mi cuaderno a internet
name: Tute Costa
email: tutecosta@protonmail.com
description: De mi cuaderno a internet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tute.github.io"
twitter_username: tutec
github_username:  tute

# Build settings
markdown: kramdown

category_title_prefix: ""
